### ISSUE TITLE
MS Store Version Immediately freezes up and goes not responding when WSL is not from MS Store

### ISSUE THREAD

**Issue by kpcintegrations** [NathanQuellec/WSL-Studio#106]
Just that, when I launch the app after installing from the ms store it just hangs and goes to a not responding window immediately upon launching. This has promise, would love to help make it work.

**Comment by kpcintegrations** [comment]
Never mind, it seems despite enabling the optional feature, and running Ubuntu and WSA, I still somehow had not installed the base WSL package from the MS Store. All is working now.

**Comment by NathanQuellec** [comment]
Hey @kpcintegrations, thanks for the feedback !

You raised something interesting. One of the functionality of WSL Studio is to detect if WSL is present or not on the system.
Usually, a pop up is displayed on your screen to inform you about that.

I will try to enhance the detection to avoid any crash.

**Comment by NathanQuellec** [comment]
And if I understand correctly, the issue appear when you have WSL that is not installed from the MS Store ?

**Comment by kpcintegrations** [comment]
Yes, that seems to be the case. Thanks for the efforts!

**Comment by NathanQuellec** [comment]
Because recents features of WSL Studio needs Microsoft Store version, it has become mandatory to have it installed. 
Hence, a verification is made at startup to see if WSL from the store is present or not. If it's not the case, WSL Studio proposes the installation to the user.
This installation ask for admin permission.

The fix is now available to the Microsoft Store.
